---
title: "Other Publications, Edited Books and Reviews"
---
&nbsp;


#### Learning from the Past: Trends in Executive Compensation over the Twentieth Century
##### CESifo Economic Studies 55 (2009): 458-481

[[Paper](https://www.dropbox.com/s/l2eq5r9ezhjjdjf/CESifo_frydman_08.pdf?raw=1)] 

&nbsp;


#### Executive Compensation in American Economic History
##### Oxford Handbook of American Economic History, Lou Cain, Price Fishback and Paul Rhode, eds., forthcoming

[[Chapter](https://www.dropbox.com/s/9v3b2fbskkqc2nu/Excomp_AEH_oxford.pdf?raw=1)] 

&nbsp;

#### The Speculation Economy: How Finance Triumphed Over Industry, by Lawrence E. Mitchell. San Francisco: Berrett-Koehler Publishers, Inc., 2008.
##### Journal of Economic History 68(2) (2008): 637-38

&nbsp;

#### The Creative Society-And the Price Americans Paid for it, by Louis Galambos. New York, NY: Cambridge University Press, 2011.
##### Journal of Economic History 72(4) (2011): 1006-08

&nbsp;

#### Comments on "Executive Compensation and Corporate Governance in the U.S.: Perceptions, Facts and Challenges" by Steven N. Kaplan.
##### Cato Papers on Public Policy vol. 2 (2012): 151-57

&nbsp;

#### Human Capital in History: The American Record (co-edited with Leah P. Boustan and Robert Margo). 
##### University of Chicago Press, 2014.

[[Introduction](http://www.nber.org/chapters/c12887.pdf)]  [[Book](http://papers.nber.org/books/bous12-1)]

&nbsp;

#### Harriman vs. Hill: Wall Street's Great Railroad War, by Larry Haeg. Minneapolis: University of Minnesota Press, 2013.
##### Journal of Economic History 75(1) (2015): 295-97
